/*global systemDictionary:true */
'use strict';

"systemDictionary" = {
    "Auto": {
        "en": "Auto",
        "de": "Auto",
        "ru": "Автоматически",
        "pt": "Auto",
        "nl": "Auto",
        "fr": "Auto",
        "it": "Auto",
        "es": "Auto",
        "pl": "Automatyczny",
        "zh-cn": "汽车"
    },
    "Confirm Password": {
        "en": "Confirm Password",
        "de": "Passwort wiederholen",
        "ru": "Подтвердите Пароль",
        "pt": "Confirme a Senha",
        "nl": "bevestig wachtwoord",
        "fr": "Confirmez le mot de passe",
        "it": "conferma password",
        "es": "Confirmar contraseña",
        "pl": "Potwierdź hasło",
        "zh-cn": "确认密码"
    },
    "Expert Settings": {
        "en": "Expert Settings",
        "de": "Experteneinstellungen",
        "ru": "Настройки эксперта",
        "pt": "Configurações para especialistas",
        "nl": "Expert instellingen",
        "fr": "Paramètres experts",
        "it": "Impostazioni avanzate",
        "es": "Configuración de expertos",
        "pl": "Ustawienia eksperta",
        "zh-cn": "专家设置"
    },
    "Host": {
        "en": "Hostname",
        "de": "Hostname",
        "ru": "Hostname",
        "pt": "Hostname",
        "nl": "Hostname",
        "fr": "Hostname",
        "it": "Hostname",
        "es": "Hostname",
        "pl": "Hostname",
        "zh-cn": "主机名"
    },
    "Main Settings": {
        "en": "Main Settings",
        "de": "Haupteinstellungen",
        "ru": "Основные параметры",
        "pt": "Configurações principais",
        "nl": "Belangrijkste instellingen",
        "fr": "Réglages principaux",
        "it": "Impostazioni principali",
        "es": "Ajustes principales",
        "pl": "Ustawienia główne",
        "zh-cn": "主要设置"
    },
    "Manual": {
        "en": "Manual",
        "de": "Manual",
        "ru": "Вручную",
        "pt": "Manual",
        "nl": "Met de hand",
        "fr": "Manuel",
        "it": "Manuale",
        "es": "Manual",
        "pl": "podręcznik",
        "zh-cn": "手册"
    },
    "Password": {
        "en": "Password",
        "de": "Passwort",
        "ru": "пароль",
        "pt": "Senha",
        "nl": "Wachtwoord",
        "fr": "Mot de passe",
        "it": "Parola d'ordine",
        "es": "Contraseña",
        "pl": "Hasło",
        "zh-cn": "密码"
    },
    "Polltime in sec.": {
        "en": "Polltime in sec.",
        "de": "Polltime in sek.",
        "ru": "Время опроса в сек.",
        "pt": "Tempo de votação em seg.",
        "nl": "Polltime in sec.",
        "fr": "Temps de scrutin en sec.",
        "it": "Polltime in sec.",
        "es": "Polltime en seg.",
        "pl": "Ankieta w sek.",
        "zh-cn": "轮询时间（以秒为单位）"
    },
    "Port": {
        "en": "Port",
        "de": "Port",
        "ru": "порт",
        "pt": "Porta",
        "nl": "Haven",
        "fr": "Port",
        "it": "Porta",
        "es": "Puerto",
        "pl": "Port",
        "zh-cn": "港口"
    },
    "Provide Lupusec Webcams": {
        "en": "Provide Lupusec Webcams",
        "de": "Lupusec Webcams einbinden",
        "ru": "Обеспечить Lupusec Веб-камеры",
        "pt": "Fornecer Webcams Lupusec",
        "nl": "Geef Lupusec Webcams",
        "fr": "Fournir des webcams Lupusec",
        "it": "Fornire webcam Lupusec",
        "es": "Proporcionar cámaras web Lupusec",
        "pl": "Udostępniaj kamery internetowe Lupusec",
        "zh-cn": "提供Lupusec网络摄像头"
    },
    "User": {
        "en": "User",
        "de": "Benutzername",
        "ru": "пользователь",
        "pt": "Do utilizador",
        "nl": "Gebruiker",
        "fr": "Utilisateur",
        "it": "Utente",
        "es": "Usuario",
        "pl": "Użytkownik",
        "zh-cn": "用户"
    },
    "Webcam IP-Address to Listen": {
        "en": "Bind address for providing Lupusec Webcams",
        "de": "Webcam Bind IP Adresse",
        "ru": "Привязать адрес для предоставления веб-камер Lupusec",
        "pt": "Endereço de ligação para fornecer webcams Lupusec",
        "nl": "Bind adres voor het verstrekken van Lupusec Webcams",
        "fr": "Adresse de liaison pour fournir des webcams Lupusec",
        "it": "Indirizzo vincolante per la fornitura di webcam Lupusec",
        "es": "Dirección de enlace para proporcionar cámaras web Lupusec",
        "pl": "Powiąż adres do udostępniania kamer internetowych Lupusec",
        "zh-cn": "绑定提供Lupusec网络摄像头的地址"
    },
    "Webcam Port": {
        "en": "Port to provide Lupusec webcam in ioBroker",
        "de": "Webcam Port",
        "ru": "Порт для предоставления веб-камеры Lupusec в ioBroker",
        "pt": "Porto para fornecer webcam Lupusec no ioBroker",
        "nl": "Poort om Lupusec-webcam in ioBroker te bieden",
        "fr": "Port fournira la webcam Lupusec sur ioBroker",
        "it": "Porta per fornire la webcam Lupusec in ioBroker",
        "es": "Puerto para proporcionar la cámara web Lupusec en ioBroker",
        "pl": "Port zapewniający kamerę internetową Lupusec w ioBroker",
        "zh-cn": "在ioBroker中提供Lupusec网络摄像头的端口"
    },
    "Webcam settings": {
        "en": "Webcam settings",
        "de": "Webcam Einstellungen",
        "ru": "Настройки веб-камеры",
        "pt": "Configurações da webcam",
        "nl": "Webcam-instellingen",
        "fr": "Paramètres de la webcam",
        "it": "Impostazioni della webcam",
        "es": "Ajustes de la webcam",
        "pl": "Ustawienia kamery internetowej",
        "zh-cn": "网络摄像头设置"
    },
    "alarm system": {
        "en": "alarm system",
        "de": "Alarmanlage",
        "ru": "аварийная система",
        "pt": "sistema de alarme",
        "nl": "alarmsysteem",
        "fr": "système d'alarme",
        "it": "sistema d'allarme",
        "es": "Sistema de alarmas",
        "pl": "system alarmowy",
        "zh-cn": "警报系统"
    },
    "https": {
        "en": "https",
        "de": "https",
        "ru": "https",
        "pt": "https",
        "nl": "https",
        "fr": "https",
        "it": "https",
        "es": "https",
        "pl": "https",
        "zh-cn": "HTTPS"
    },
    "on save adapter restarts with new config immediately": {
        "en": "on save adapter restarts with new config immediately",
        "de": "Beim Speichern von Einstellungen wird der Adapter sofort neu gestartet.",
        "ru": "При сохранении настроек адаптера он сразу же перезапускается",
        "pt": "no adaptador de salvar reinicia com nova configuração imediatamente",
        "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config",
        "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement",
        "it": "su save adapter si riavvia immediatamente con la nuova configurazione",
        "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato",
        "pl": "na karcie save natychmiast uruchamia się z nową konfiguracją",
        "zh-cn": "保存适配器立即重新启动新配置"
    },
    "template adapter settings": {
        "en": "template adapter settings",
        "de": "Beispiel",
        "ru": "Пример",
        "pt": "configurações do adaptador de modelo",
        "nl": "sjabloon-adapterinstellingen",
        "fr": "paramètres de l'adaptateur de modèle",
        "it": "impostazioni dell'adattatore del modello",
        "es": "configuración del adaptador de plantilla",
        "pl": "ustawienia adaptera szablonu",
        "zh-cn": "模板适配器设置"
    },
    "Lupusec doorsensor for Nuki": {
        "en": "Lupusec doorsensor for Nuki",
        "de": "Lupusec Türsensor für Nuki",
        "ru": "Lupusec дверной датчик для Nuki",
        "pt": "Sensor de porta Lupusec para Nuki",
        "nl": "Lupusec deursensor voor Nuki",
        "fr": "Capteur de porte Lupusec pour Nuki",
        "it": "Sensore per porte Lupusec per Nuki",
        "es": "Sensor de puerta Lupusec para Nuki",
        "pl": "Czujnik drzwi Lupusec dla Nuki",
        "zh-cn": "适用于Nuki的Lupusec门磁"
    },
    "Nuki settings": {
        "en": "Nuki settings",
        "de": "Nuki Einstellungen",
        "ru": "Настройки нуки",
        "pt": "Configurações de Nuki",
        "nl": "Nuki-instellingen",
        "fr": "Paramètres Nuki",
        "it": "Impostazioni di Nuki",
        "es": "Ajustes de Nuki",
        "pl": "Ustawienia Nuki",
        "zh-cn": "Nuki设置"
    },
    "Allow to transfer error logs to the external ioBroker Sentry system. Usernames, Passwords, Tokens, ... will be NOT be transferd.": {
        "en": "Allow to transfer error logs to the external ioBroker Sentry system. Usernames, Passwords, Tokens, ... will be NOT be transferd.",
        "de": "Erlaube das weiterleiten von Fehlerprotokollen an die externe ioBroker Sentry Anwendung. Benutzernamen, Passwörter, Tokens, ... werden NICHT übertragen.",
        "ru": "Разрешить перенос ошибок на внешнюю систему ioBroker Sentry. Имена пользователей, пароли, токены, ... НЕ будут передаваться.",
        "pt": "Permita o armazenamento de erros no sistema ioBroker Sentry externo. Nomes de usuário, senhas, tokens, ... NÃO serão transferidos.",
        "nl": "Sta looging van fouten toe aan het externe ioBroker Sentry-systeem. Gebruikersnamen, wachtwoorden, tokens, ... worden NIET overgedragen.",
        "fr": "Autorise le repérage des erreurs sur le système ioBroker Sentry externe. Les noms d'utilisateur, mots de passe, jetons, ... ne seront PAS transférés.",
        "it": "Consentire il looging degli errori sul sistema ioBroker Sentry esterno. Nomi utente, password, token, ... NON saranno trasferiti.",
        "es": "Permitir el registro de errores en el sistema externo ioBroker Sentry. Los nombres de usuario, contraseñas, tokens, ... NO serán transferidos.",
        "pl": "Zezwalaj na zapętlanie błędów w zewnętrznym systemie ioBroker Sentry. Nazwy użytkowników, hasła, tokeny, ... NIE zostaną przeniesione.",
        "zh-cn": "允许将错误清除到外部ioBroker Sentry系统。用户名，密码，令牌……将不会被转移。"
    }
}