/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Auto": {                                        "en": "Auto",                                            "de": "Auto",                                            "ru": "Автоматически",                                   "pt": "Auto",                                            "nl": "Auto",                                            "fr": "Auto",                                            "it": "Auto",                                            "es": "Auto",                                            "pl": "Automatyczny",                                    "zh-cn": "汽车"},
    "Confirm Password": {                            "en": "Confirm Password",                                "de": "Passwort wiederholen",                            "ru": "Подтвердите Пароль",                              "pt": "Confirme a Senha",                                "nl": "bevestig wachtwoord",                             "fr": "Confirmez le mot de passe",                       "it": "conferma password",                               "es": "Confirmar contraseña",                            "pl": "Potwierdź hasło",                                 "zh-cn": "确认密码"},
    "Host": {                                        "en": "Hostname",                                        "de": "Hostname",                                        "ru": "Hostname",                                        "pt": "Hostname",                                        "nl": "Hostname",                                        "fr": "Hostname",                                        "it": "Hostname",                                        "es": "Hostname",                                        "pl": "Hostname",                                        "zh-cn": "主机名"},
    "Manual": {                                      "en": "Manual",                                          "de": "Manual",                                          "ru": "Вручную",                                         "pt": "Manual",                                          "nl": "Met de hand",                                     "fr": "Manuel",                                          "it": "Manuale",                                         "es": "Manual",                                          "pl": "podręcznik",                                      "zh-cn": "手册"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "порт",                                            "pt": "Porta",                                           "nl": "Haven",                                           "fr": "Port",                                            "it": "Porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "港口"},
    "User": {                                        "en": "User",                                            "de": "Benutzername",                                    "ru": "пользователь",                                    "pt": "Do utilizador",                                   "nl": "Gebruiker",                                       "fr": "Utilisateur",                                     "it": "Utente",                                          "es": "Usuario",                                         "pl": "Użytkownik",                                      "zh-cn": "用户"},
    "alarm system": {                                "en": "alarm system",                                    "de": "Alarmanlage",                                     "ru": "аварийная система",                               "pt": "sistema de alarme",                               "nl": "alarmsysteem",                                    "fr": "système d'alarme",                                "it": "sistema d'allarme",                               "es": "Sistema de alarmas",                              "pl": "system alarmowy",                                 "zh-cn": "警报系统"},
    "https": {                                       "en": "https",                                           "de": "https",                                           "ru": "https",                                           "pt": "https",                                           "nl": "https",                                           "fr": "https",                                           "it": "https",                                           "es": "https",                                           "pl": "https",                                           "zh-cn": "HTTPS"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen wird der Adapter sofort neu gestartet.", "ru": "При сохранении настроек адаптера он сразу же перезапускается", "pt": "no adaptador de salvar reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato", "pl": "na karcie save natychmiast uruchamia się z nową konfiguracją", "zh-cn": "保存适配器立即重新启动新配置"},
    "template adapter settings": {                   "en": "template adapter settings",                       "de": "Beispiel",                                        "ru": "Пример",                                          "pt": "configurações do adaptador de modelo",            "nl": "sjabloon-adapterinstellingen",                    "fr": "paramètres de l'adaptateur de modèle",            "it": "impostazioni dell'adattatore del modello",        "es": "configuración del adaptador de plantilla",        "pl": "ustawienia adaptera szablonu",                    "zh-cn": "模板适配器设置"},
};