/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "Auto": {
    "en": "Auto",
    "de": "Auto",
    "ru": "Автоматически",
    "pt": "Auto",
    "nl": "Auto",
    "fr": "Auto",
    "it": "Auto",
    "es": "Auto",
    "pl": "Auto"
  },
  "Manual": {
    "en": "Manual",
    "de": "Manual",
    "ru": "Вручную",
    "pt": "Manual",
    "nl": "Met de hand",
    "fr": "Manuel",
    "it": "Manuale",
    "es": "Manual",
    "pl": "Manual"
  },
  "Expert Settings": {
    "en": "Expert Settings",
    "de": "Experteneinstellungen",
    "ru": "Настройки эксперта",
    "pt": "Configurações de especialistas",
    "nl": "Expertinstellingen",
    "fr": "Paramètres experts",
    "it": "Impostazioni esperte",
    "es": "Configuraciones de expertos",
    "pl": "Ustawienia eksperta",
    "zh-cn": "专家设定"
  },
  "on save adapter restarts with new config immediately": {
    "en": "on save adapter restarts with new config immediately",
    "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
    "ru": "При сохранении настроек адаптера он сразу же перезапускается",
    "pt": "no adaptador de salvar reinicia com nova configuração imediatamente",
    "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config",
    "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement",
    "it": "su save adapter si riavvia immediatamente con la nuova configurazione",
    "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato",
    "pl": "on save adapter restarts with new config immediately"
  },
  "User": {
    "en": "User",
    "de": "Benutzer",
    "ru": "пользователь",
    "pt": "Do utilizador",
    "nl": "Gebruiker",
    "fr": "Utilisateur",
    "it": "Utente",
    "es": "Usuario",
    "pl": "Użytkownik"
  },
  "Password": {
    "en": "Password",
    "de": "Passwort",
    "ru": "пароль",
    "pt": "Senha",
    "nl": "Wachtwoord",
    "fr": "Mot de passe",
    "it": "Parola d'ordine",
    "es": "Contraseña",
    "pl": "Hasło"
  },
  "Confirm Password": {
    "en": "Confim Password",
    "de": "Bestätige das Passwort",
    "ru": "Подтвердите Пароль",
    "pt": "Confirme a Senha",
    "nl": "bevestig wachtwoord",
    "fr": "Confirmez le mot de passe",
    "it": "conferma password",
    "es": "Confirmar contraseña",
    "pl": "Potwierdź hasło"
  },
  "Password Enable": {
    "en": "Login with password",
    "de": "Einloggen mit Passwort",
    "ru": "Вход с паролем",
    "pt": "Login com senha",
    "nl": "Inloggen met wachtwoord",
    "fr": "Se connecter avec mot de passe",
    "it": "Accedi con password",
    "es": "Iniciar sesión con contraseña",
    "pl": "Zaloguj się za pomocą hasła"
  },
  "Host": {
    "en": "Hostname",
    "de": "Hostname",
    "ru": "Hostname",
    "pt": "nome de anfitrião",
    "nl": "Hostnaam",
    "fr": "Nom d'hôte",
    "it": "Nome host",
    "es": "Nombre de host",
    "pl": "Nazwa hosta",
    "zh-cn": "主机名"
  },
  "Main Settings": {
    "en": "Main Settings",
    "de": "Haupteinstellungen",
    "ru": "Основные настройки",
    "pt": "Configurações principais",
    "nl": "Belangrijkste instellingen",
    "fr": "Réglages principaux",
    "it": "Impostazioni principali",
    "es": "Ajustes principales",
    "pl": "Ustawienia główne",
    "zh-cn": "主要设定"
  },
  "Polltime in sec.": {
    "en": "Polltime in sec.",
    "de": "Polltime in sek.",
    "ru": "Время опроса в сек.",
    "pt": "Tempo de votação em seg.",
    "nl": "Polltime in sec.",
    "fr": "Temps de scrutin en sec.",
    "it": "Polltime in sec.",
    "es": "Polltime en seg.",
    "pl": "Ankieta w sek.",
    "zh-cn": "轮询时间（以秒为单位）"
  },
  "Lupusec doorsensor for Nuki": {
    "en": "Lupusec doorsensor for Nuki",
    "de": "Lupusec Türsensor für Nuki",
    "ru": "Lupusec дверной датчик для Nuki",
    "pt": "Sensor de porta Lupusec para Nuki",
    "nl": "Lupusec deursensor voor Nuki",
    "fr": "Capteur de porte Lupusec pour Nuki",
    "it": "Sensore per porte Lupusec per Nuki",
    "es": "Sensor de puerta Lupusec para Nuki",
    "pl": "Czujnik drzwi Lupusec dla Nuki",
    "zh-cn": "适用于Nuki的Lupusec门磁"
  },
  "Nuki settings": {
    "en": "Nuki settings",
    "de": "Nuki Einstellungen",
    "ru": "Настройки нуки",
    "pt": "Configurações de Nuki",
    "nl": "Nuki-instellingen",
    "fr": "Paramètres Nuki",
    "it": "Impostazioni di Nuki",
    "es": "Ajustes de Nuki",
    "pl": "Ustawienia Nuki",
    "zh-cn": "Nuki设置"
  },
  "Provide Lupusec Webcams": {
    "en": "Provide Lupusec Webcams",
    "de": "Webcams einbinden",
    "ru": "Обеспечить Lupusec Веб-камеры",
    "pt": "Fornecer webcams Lupusec",
    "nl": "Zorg voor Lupusec-webcams",
    "fr": "Fournir des webcams Lupusec",
    "it": "Fornire webcam Lupusec",
    "es": "Proporcionar cámaras web Lupusec",
    "pl": "Zapewnij kamery internetowe Lupusec",
    "zh-cn": "提供Lupusec网络摄像头"
  },
  "Webcam IP-Address to Listen": {
    "en": "Webcam IP-Address to Listen",
    "de": "Webcam IP-Adresse zum Abhören",
    "ru": "IP-адрес веб-камеры для прослушивания",
    "pt": "Endereço IP da webcam para escutar",
    "nl": "IP-adres van webcam om te luisteren",
    "fr": "Adresse IP de la webcam à écouter",
    "it": "Indirizzo IP della webcam da ascoltare",
    "es": "Dirección IP de la cámara web para escuchar",
    "pl": "Adres IP kamery internetowej do słuchania",
    "zh-cn": "网络摄像头IP地址以收听"
  },
  "Webcam Port": {
    "en": "Port to provide Lupusec webcam in ioBroker",
    "de": "Webcam Port",
    "ru": "Порт веб-камеры",
    "pt": "Porta da webcam",
    "nl": "Webcam-poort",
    "fr": "Port webcam",
    "it": "Porta della webcam",
    "es": "Puerto de webcam",
    "pl": "Port kamery internetowej",
    "zh-cn": "网络摄像头端口"
  },
  "Webcam settings": {
    "en": "Webcam settings",
    "de": "Webcam Einstellungen",
    "ru": "Настройки веб-камеры",
    "pt": "Configurações da webcam",
    "nl": "Webcam-instellingen",
    "fr": "Paramètres de la webcam",
    "it": "Impostazioni della webcam",
    "es": "Configuraciones de webcam",
    "pl": "Ustawienia kamery internetowej",
    "zh-cn": "网络摄像头设置"
  },
  "alarm system": {
    "en": "alarm system",
    "de": "Alarmanlage",
    "ru": "сигнализация",
    "pt": "sistema de alarme",
    "nl": "alarmsysteem",
    "fr": "système d'alarme",
    "it": "sistema d'allarme",
    "es": "Sistema de alarmas",
    "pl": "system alarmowy",
    "zh-cn": "警报系统"
  },
  "https": {
    "en": "https",
    "de": "https",
    "ru": "HTTPS",
    "pt": "https",
    "nl": "https",
    "fr": "https",
    "it": "https",
    "es": "https",
    "pl": "https",
    "zh-cn": "https"
  },
  "Allow to transfer errors if the adapter crash. Private data like usernames, passwords, tokens, ... will be NOT be transferd.": {
    "en": "Allow to transfer errors if the adapter crash. Private data like usernames, passwords, tokens, ... will be NOT be transferd.",
    "de": "Erlaube das weiterleiten von Fehlern wenn der Adapter abstürtzt. Private Daten wie z.B. Benutzername, Passwort, Token, ... werden NICHT übertragen.",
    "ru": "Разрешить передавать ошибки в случае сбоя адаптера. Личные данные, такие как имена пользователей, пароли, токены, ... НЕ будут передаваться.",
    "pt": "Permitir a transferência de erros se o adaptador travar. Dados privados como nomes de usuário, senhas, tokens, ... NÃO serão transferidos.",
    "nl": "Sta toe om fouten over te dragen als de adapter crasht. Privégegevens zoals gebruikersnamen, wachtwoorden, tokens, ... worden NIET overgedragen.",
    "fr": "Permet de transférer des erreurs en cas de panne de l'adaptateur. Les données privées comme les noms d'utilisateur, les mots de passe, les jetons, ... ne seront PAS transférées.",
    "it": "Consentire il trasferimento degli errori in caso di arresto anomalo dell'adattatore. I dati privati come nomi utente, password, token, ... NON saranno trasferiti.",
    "es": "Permita transferir errores si el adaptador falla. NO se transferirán datos privados como nombres de usuario, contraseñas, tokens, ...",
    "pl": "Zezwól na przesyłanie błędów w przypadku awarii adaptera. Prywatne dane, takie jak nazwy użytkowników, hasła, tokeny, ... NIE zostaną przeniesione.",
    "zh-cn": "如果适配器崩溃，则允许传输错误。用户名，密码，令牌等私密数据将不会被传输。"
  }
};
